/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module intercambiador (
  input a3,
  input a2,
  input a1,
  input a0,
  input b3,
  input b2,
  input b1,
  input b0,
  input op,
  output ma,
  output eq,
  output me,
  output d0,
  output d1,
  output d2,
  output d3,
  output c0,
  output c1,
  output c2,
  output c3,
  output ne
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  assign c3 = (a3 | (b3 & op));
  assign s7 = ~ a3;
  assign s6 = ~ a2;
  assign s5 = ~ a1;
  assign s4 = ~ a0;
  assign s3 = ~ b3;
  assign s2 = ~ b2;
  assign s1 = ~ b1;
  assign s0 = ~ b0;
  assign s8 = ~ op;
  assign ma = ((a0 & s0 & s1 & s2 & s3) | (a0 & a3 & s0 & s1 & s2) | (a0 & a2 & s0 & s1 & s3) | (a0 & a2 & a3 & s0 & s1) | (a0 & a1 & s0 & s2 & s3) | (a0 & a1 & a3 & s0 & s2) | (a0 & a1 & a2 & s0 & s3) | (a0 & a1 & a2 & a3 & s0) | (a1 & s1 & s2 & s3) | (a1 & a3 & s1 & s2) | (a1 & a2 & s1 & s3) | (a1 & a2 & a3 & s1) | (a2 & s2 & s3) | (a2 & a3 & s2) | (a3 & s3));
  assign eq = ((s4 & s5 & s6 & s7 & s0 & s1 & s2 & s3) | (a0 & s5 & s6 & s7 & b0 & s1 & s2 & s3) | (s4 & a1 & s6 & s7 & s0 & b1 & s2 & s3) | (a0 & a1 & s6 & s7 & b0 & b1 & s2 & s3) | (s4 & s5 & a2 & s7 & s0 & s1 & b2 & s3) | (a0 & s5 & a2 & s7 & b0 & s1 & b2 & s3) | (s4 & a1 & a2 & s7 & s0 & b1 & b2 & s3) | (a0 & a1 & a2 & s7 & b0 & b1 & b2 & s3) | (s4 & s5 & s6 & a3 & s0 & s1 & s2 & b3) | (a0 & s5 & s6 & a3 & b0 & s1 & s2 & b3) | (s4 & a1 & s6 & a3 & s0 & b1 & s2 & b3) | (a0 & a1 & s6 & a3 & b0 & b1 & s2 & b3) | (s4 & s5 & a2 & a3 & s0 & s1 & b2 & b3) | (a0 & s5 & a2 & a3 & b0 & s1 & b2 & b3) | (s4 & a1 & a2 & a3 & s0 & b1 & b2 & b3) | (a0 & a1 & a2 & a3 & b0 & b1 & b2 & b3));
  assign me = ((s4 & b0 & b1 & b2 & b3) | (s4 & s7 & b0 & b1 & b2) | (s4 & s6 & b0 & b1 & b3) | (s4 & s6 & s7 & b0 & b1) | (s4 & s5 & b0 & b2 & b3) | (s4 & s5 & s7 & b0 & b2) | (s4 & s5 & s6 & b0 & b3) | (s4 & s5 & s6 & s7 & b0) | (s5 & b1 & b2 & b3) | (s5 & s7 & b1 & b2) | (s5 & s6 & b1 & b3) | (s5 & s6 & s7 & b1) | (s6 & b2 & b3) | (s6 & s7 & b2) | (s7 & b3));
  assign d0 = ((a0 & s5 & b1 & b2 & b3 & op) | (a0 & s5 & s7 & b1 & b2 & op) | (a0 & s5 & s6 & b1 & b3 & op) | (a0 & s5 & s6 & s7 & b1 & op) | (a0 & s6 & b2 & b3 & op) | (a0 & s6 & s7 & b2 & op) | (a0 & s7 & b3 & op) | (a0 & b0) | (a1 & b0 & s1 & s2 & s3) | (a1 & a3 & b0 & s1 & s2) | (a1 & a2 & b0 & s1 & s3) | (a1 & a2 & a3 & b0 & s1) | (a2 & b0 & s2 & s3) | (a2 & a3 & b0 & s2) | (a3 & b0 & s3) | (b0 & s8));
  assign d1 = ((a1 & s6 & b2 & b3 & op) | (a1 & s6 & s7 & b2 & op) | (a1 & s7 & b3 & op) | (a1 & b1) | (a2 & b1 & s2 & s3) | (a2 & a3 & b1 & s2) | (a3 & b1 & s3) | (b1 & s8));
  assign d2 = ((a2 & s7 & b3 & op) | (a2 & b2) | (a3 & b2 & s3) | (b2 & s8));
  assign d3 = ((a3 & b3) | (b3 & s8));
  assign c0 = ((a0 & s1 & s2 & s3) | (a0 & a3 & s1 & s2) | (a0 & a2 & s1 & s3) | (a0 & a2 & a3 & s1) | (a0 & a1 & s2 & s3) | (a0 & a2 & s2 & s3) | (a0 & a1 & a3 & s2) | (a0 & a2 & a3 & s2) | (a0 & a1 & a2 & s3) | (a0 & a1 & a2 & a3) | (a0 & a3 & s3) | (a0 & s8) | (s5 & b0 & b2 & b3 & op) | (s5 & s7 & b0 & b2 & op) | (s5 & s6 & b0 & b3 & op) | (s5 & s6 & s7 & b0 & op) | (s6 & b0 & b1 & b3 & op) | (s6 & s7 & b0 & b1 & op) | (s6 & b0 & b2 & b3 & op) | (s6 & s7 & b0 & b2 & op) | (s7 & b0 & b1 & b2 & op) | (s7 & b0 & b3 & op) | (b0 & b1 & b2 & b3 & op));
  assign c1 = ((a1 & s2 & s3) | (a1 & a3 & s2) | (a1 & a2 & s3) | (a1 & a3 & s3) | (a1 & a2 & a3) | (a1 & s8) | (s6 & b1 & b3 & op) | (s6 & s7 & b1 & op) | (s7 & b1 & b2 & op) | (s7 & b1 & b3 & op) | (b1 & b2 & b3 & op));
  assign c2 = ((a2 & s8) | (a2 & s3) | (a2 & a3) | (s7 & b2 & op) | (b2 & b3 & op));
  assign ne = ((s4 & b0 & b1 & b2 & b3 & op) | (s4 & s7 & b0 & b1 & b2 & op) | (s4 & s6 & b0 & b1 & b3 & op) | (s4 & s6 & s7 & b0 & b1 & op) | (s4 & s5 & b0 & b2 & b3 & op) | (s4 & s5 & s7 & b0 & b2 & op) | (s4 & s5 & s6 & b0 & b3 & op) | (s4 & s5 & s6 & s7 & b0 & op) | (s5 & b1 & b2 & b3 & op) | (s5 & s7 & b1 & b2 & op) | (s5 & s6 & b1 & b3 & op) | (s5 & s6 & s7 & b1 & op) | (s6 & b2 & b3 & op) | (s6 & s7 & b2 & op) | (s7 & b3 & op));
endmodule
