/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module seg7 (
  input f3,
  input f2,
  input f1,
  input f0,
  output a,
  output b,
  output c,
  output d,
  output e,
  output f,
  output g
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign s2 = ~ f3;
  assign s1 = ~ f2;
  assign s0 = ~ f1;
  assign s3 = ~ f0;
  assign a = ((f0 & s0 & s1 & s2) | (s3 & s0 & f2));
  assign b = ((f0 & s0 & f2) | (s3 & f1 & f2));
  assign c = (s3 & f1 & s1);
  assign d = ((f0 & s0 & s1) | (s3 & s0 & f2) | (f0 & f1 & f2));
  assign e = ((f0 & s2) | (f0 & s0) | (f0 & f2) | (s0 & f2));
  assign f = ((f0 & s1 & s2) | (f0 & f1) | (f1 & s1));
  assign g = ((f0 & f1 & f2) | (f0 & f1 & f3) | (s0 & s1 & s2));
endmodule
