/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module halfadder (
  input A,
  input B,
  output Co,
  output S
);
  assign S = (A ^ B);
  assign Co = (A & B);
endmodule

module fulladder (
  input A,
  input B,
  input Ci,
  output Co,
  output S
);
  wire s0;
  wire s1;
  wire s2;
  halfadder halfadder_i0 (
    .A( A ),
    .B( B ),
    .Co( s2 ),
    .S( s0 )
  );
  halfadder halfadder_i1 (
    .A( Ci ),
    .B( s0 ),
    .Co( s1 ),
    .S( S )
  );
  assign Co = (s2 | s1);
endmodule
